name: main
on:
  push:
    tags:
      - 'v*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Meta
      id: shell-vars
      run: |
        tag=$(git tag --list --sort=taggerdate | tail -n 1)
        echo "::set-output name=TAG::$tag"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push ubuntu image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile-ubuntu
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fsjob:${{ steps.shell-vars.outputs.TAG }}-ubuntu20.04
    - name: Build and push fedora image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile-fedora
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fsjob:${{ steps.shell-vars.outputs.TAG }}-fedora33